export const UserActionTypes = {
  CREATE_USER_START: " CREATE_USER_START",
  CREATE_USER_SUCCESS: " CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: " CREATE_USER_FAIL",

  LOGIN_USER_START: " LOGIN_USER_START",
  LOGIN_USER_SUCCESS: " LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: " LOGIN_USER_FAIL",

  LOGOUT_USER_START: " LOGOUT_USER_START",
  LOGOUT_USER_SUCCESS: " LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAIL: " LOGOUT_USER_FAIL",
};

export const CartActionTypes={
  ADDTOCART_START: "ADDTOCART_START",
  ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
  ADDTOCART_FAIL: "ADDTOCART_FAIL",

  REMOVECART_START: "REMOVECART_START",
  REMOVECART_SUCCESS: "REMOVECART_SUCCESS",
  REMOVECART_FAIL: "REMOVECART_FAIL",
}

export const ClientActionTypes = {
  GET_CLIENT_LIST_START: "GET_CLIENT_LIST_START",
  GET_CLIENT_LIST_SUCCESS: "GET_CLIENT_LIST_SUCCESS",
  GET_CLIENT_LIST_FAIL: "GET_CLIENT_LIST_FAIL",

  POST_MANAGER_INFO_START: "POST_MANAGER_INFO_START",
  POST_MANAGER_INFO_SUCCESS: "POST_MANAGER_INFO_SUCCESS",
  POST_MANAGER_INFO_FAIL: "POST_MANAGER_INFO_FAIL",

  POST_ADD_CATAGORY_START: "POST_ADD_CATAGORY_START",
  POST_ADD_CATAGORY_SUCCESS: "POST_ADD_CATAGORY_SUCCESS",
  POST_ADD_CATAGORY_FAIL: "POST_ADD_CATAGORY_FAIL",

  POST_ADD_SUB_CATAGORY_START: "POST_ADD_SUB_CATAGORY_START",
  POST_ADD_SUB_CATAGORY_SUCCESS: "POST_ADD_SUB_CATAGORY_SUCCESS",
  POST_ADD_SUB_CATAGORY_FAIL: "POST_ADD_SUB_CATAGORY_FAIL",

  POST_ADD_WEBSITE_INFO_START: "POST_ADD_WEBSITE_INFO_START",
  POST_ADD_WEBSITE_INFO_SUCCESS: "POST_ADD_WEBSITE_INFO_SUCCESS",
  POST_ADD_WEBSITE_INFO_FAIL: "POST_ADD_WEBSITE_INFO_FAIL",

  EDIT_SUB_CATAGORY_START: "EDIT_SUB_CATAGORY_START",
  EDIT_SUB_CATAGORY_SUCCESS: "EDIT_SUB_CATAGORY_SUCCESS",
  EDIT_SUB_CATAGORY_FAIL: "EDIT_SUB_CATAGORY_FAIL",

  GET_CLIENT_DETAILS_START: "GET_CLIENT_DETAILS_START",
  GET_CLIENT_DETAILS_SUCCESS: "GET_CLIENT_DETAILS_SUCCESS",
  GET_CLIENT_DETAILS_FAIL: "GET_CLIENT_DETAILS_FAIL",

  EDIT_CLIENT_DETAILS_START: "EDIT_CLIENT_DETAILS_START",
  EDIT_CLIENT_DETAILS_SUCCESS: "EDIT_CLIENT_DETAILS_SUCCESS",
  EDIT_CLIENT_DETAILS_FAIL: "EDIT_CLIENT_DETAILS_FAIL",

  GET_CLIENT_PRODUCTS_START: "GET_CLIENT_PRODUCTS_START",
  GET_CLIENT_PRODUCTS_SUCCESS: "GET_CLIENT_PRODUCTS_SUCCESS",
  GET_CLIENT_PRODUCTS_FAIL: "GET_CLIENT_PRODUCTS_FAIL",

  GET_CLIENT_WEBSITE_INFO_START: "GET_CLIENT_WEBSITE_INFO_START",
  GET_CLIENT_WEBSITE_INFO_SUCCESS: "GET_CLIENT_WEBSITE_INFO_SUCCESS",
  GET_CLIENT_WEBSITE_INFO_FAIL: "GET_CLIENT_WEBSITE_INFO_FAIL",


  PUT_CLIENT_WEBSITE_INFO_START: "PUT_CLIENT_WEBSITE_INFO_START",
  PUT_CLIENT_WEBSITE_INFO_SUCCESS: "PUT_CLIENT_WEBSITE_INFO_SUCCESS",
  PUT_CLIENT_WEBSITE_INFO_FAIL: "PUT_CLIENT_WEBSITE_INFO_FAIL",

  REMOVE_CATAGORY_START: "REMOVE_CATAGORY_START",
  REMOVE_CATAGORY_SUCCESS: "REMOVE_CATAGORY_SUCCESS",
  REMOVE_CATAGORY_FAIL: "REMOVE_CATAGORY_FAIL",

  GET_CLIENT_PRODUCTS_LIST_START: "GET_CLIENT_PRODUCTS_LIST_START",
  GET_CLIENT_PRODUCTS_LIST_SUCCESS: "GET_CLIENT_PRODUCTS_LIST_SUCCESS",
  GET_CLIENT_PRODUCTS_LIST_FAIL: "GET_CLIENT_PRODUCTS_LIST_FAIL",

  SET_SETP: "SET_SETP",
};
