export const CartActionTypes={
  ADDTOCART_START: "ADDTOCART_START",
  ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
  ADDTOCART_FAIL: "ADDTOCART_FAIL",

  REMOVECART_START: "REMOVECART_START",
  REMOVECART_SUCCESS: "REMOVECART_SUCCESS",
  REMOVECART_FAIL: "REMOVECART_FAIL",

  REMOVEQUANTITY_START: "REMOVEQUANTITY_START",
  REMOVEQUANTITY_SUCCESS: "REMOVEQUANTITY_SUCCESS",
  REMOVEQUANTITY_FAIL: "REMOVEQUANTITY_FAIL",
}


